#!/usr/bin/env python3
"""Turns a BDF bitmap font into the `const` glyph table alliumd's on-screen indicator draws with.

Only ASCII 32..126 is emitted, one `[u8; rows]` per glyph with bit 7 as the leftmost column -- the
same layout as the BDF's own hex rows, so the table can be checked against the source by eye. Every
codepoint in that range must be present and no glyph may ink beyond the cell width; either failure
stops generation rather than shipping a table with holes.

    bdf_to_rust.py scripts/fonts/spleen-6x12.bdf crates/alliumd/src/osd_font.rs --version 2.2.0
"""
import argparse
import hashlib
import sys
from pathlib import Path

FIRST, LAST = 32, 126
WRAP = 100


def parse_header(lines):
    header = {}
    for line in lines:
        if line.startswith("STARTCHAR"):
            break
        key, _, value = line.partition(" ")
        header[key] = value.strip()
    return header


def parse_glyphs(lines):
    """Yields (encoding, bbx, rows) for every glyph in the file."""
    it = iter(lines)
    for line in it:
        if not line.startswith("STARTCHAR"):
            continue
        encoding = None
        bbx = None
        rows = []
        for line in it:
            if line.startswith("ENCODING"):
                parts = line.split()
                # `ENCODING -1 n` is an unmapped glyph
                encoding = int(parts[1]) if len(parts) == 2 else -1
            elif line.startswith("BBX"):
                bbx = tuple(int(v) for v in line.split()[1:5])
            elif line.startswith("BITMAP"):
                for line in it:
                    if line.startswith("ENDCHAR"):
                        break
                    rows.append(int(line.strip(), 16))
                break
        if encoding is not None and bbx is not None:
            yield encoding, bbx, rows


def wrap_comment(text):
    words, out, line = text.split(), [], "//!"
    for word in words:
        if len(line) + 1 + len(word) > WRAP:
            out.append(line)
            line = "//! " + word
        else:
            line += " " + word
    out.append(line)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("bdf", type=Path)
    ap.add_argument("out", type=Path)
    ap.add_argument("--version", required=True, help="the font release the BDF came from")
    ap.add_argument("--url", default="https://github.com/fcambus/spleen")
    args = ap.parse_args()

    data = args.bdf.read_bytes()
    lines = data.decode("utf-8").splitlines()
    header = parse_header(lines)

    fw, fh, fx, fy = (int(v) for v in header["FONTBOUNDINGBOX"].split())
    if fw > 8:
        sys.exit(f"cell is {fw} wide; one byte per row only holds 8 columns")
    if fh < 1:
        sys.exit("cell has no rows")
    ink_mask = 0xFF & ~((1 << (8 - fw)) - 1)  # the bits that lie inside the cell
    last_column = 1 << (8 - fw)  # the bit for column fw - 1

    glyphs = {}
    uses_last_column = []
    for encoding, (bw, bh, bx, by), rows in parse_glyphs(lines):
        if not FIRST <= encoding <= LAST:
            continue
        if len(rows) != bh:
            sys.exit(f"glyph {encoding}: BBX says {bh} rows, BITMAP has {len(rows)}")
        top = (fy + fh) - (by + bh)
        shift = bx - fx
        if top < 0 or top + bh > fh or shift < 0:
            sys.exit(f"glyph {encoding}: BBX {bw}x{bh}+{bx}+{by} does not fit the cell")
        cell = [0] * fh
        for r, bits in enumerate(rows):
            bits = (bits >> shift) & 0xFF
            if bits & ~ink_mask:
                sys.exit(f"glyph {encoding}: ink beyond column {fw - 1}")
            if bits & last_column:
                uses_last_column.append(encoding)
            cell[top + r] |= bits
        glyphs[encoding] = cell

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        sys.exit(f"missing glyphs for codepoints: {missing}")

    digest = hashlib.sha256(data).hexdigest()
    copyright_ = header.get("COPYRIGHT", "").strip('"')
    font_name = header.get("FONT", "").strip('"') or args.bdf.name

    out = []
    out.append("//! Glyphs for the on-screen indicator. Generated by scripts/fonts/bdf_to_rust.py; do not edit.")
    out.append("//!")
    out += wrap_comment(
        f"Source: {args.bdf.name} from {args.url}, release {args.version} (FONT_VERSION "
        f"\"{header.get('FONT_VERSION', '?').strip(chr(34))}\", sha256 {digest}). {copyright_}."
    )
    out += wrap_comment(
        "Licensed under the BSD 2-Clause License; the full text ships beside the other font "
        "licences as static/.allium/fonts/licenses/Spleen-BSD-2-Clause.txt."
    )
    out.append("")
    out.append("/// Columns in a glyph cell; a row's leftmost column is bit 7")
    out.append(f"pub const GLYPH_WIDTH: usize = {fw};")
    out.append("/// Rows in a glyph cell, one byte each, top row first")
    out.append(f"pub const GLYPH_HEIGHT: usize = {fh};")
    out.append("/// The character `GLYPHS[0]` draws; the table runs contiguously through `'~'`")
    out.append("pub const FIRST_CHAR: char = ' ';")
    out.append(f"/// Bit 7 is column 0; bits below `8 - GLYPH_WIDTH` are always zero")
    out.append("#[rustfmt::skip]")
    out.append(f"pub const GLYPHS: [[u8; GLYPH_HEIGHT]; {LAST - FIRST + 1}] = [")
    for code in range(FIRST, LAST + 1):
        cells = ", ".join(f"0x{b:02X}" for b in glyphs[code])
        label = "'\\''" if code == 39 else ("'\\\\'" if code == 92 else f"'{chr(code)}'")
        out.append(f"    [{cells}], // {label}")
    out.append("];")
    out.append("")

    args.out.write_text("\n".join(out), encoding="utf-8", newline="\n")
    note = f", {len(uses_last_column)} glyphs ink the last column" if uses_last_column else ""
    print(f"{args.out}: {len(glyphs)} glyphs, {fw}x{fh} cells from {font_name}{note}")


if __name__ == "__main__":
    main()
